-- Peachpuff syntax color scheme
local lexers = vis.lexers

lexers.STYLE_DEFAULT = 'back:default,fore:default'
lexers.STYLE_NOTHING = 'back:white'
lexers.STYLE_CLASS = 'fore:black'
lexers.STYLE_COMMENT = 'fore:blue'
lexers.STYLE_CONSTANT = 'fore:red'
lexers.STYLE_DEFINITION = 'fore:black'
lexers.STYLE_ERROR = 'fore:7,back:1,bold'
lexers.STYLE_FUNCTION = 'fore:black'
lexers.STYLE_KEYWORD = 'fore:yellow,notbold'
lexers.STYLE_LABEL = 'fore:black'
lexers.STYLE_NUMBER = 'fore:red'
lexers.STYLE_OPERATOR = 'fore:black'
lexers.STYLE_REGEX = 'fore:red'
lexers.STYLE_STRING = 'fore:red'
lexers.STYLE_PREPROCESSOR = 'fore:black'
lexers.STYLE_TAG = 'fore:black'
lexers.STYLE_TYPE = 'fore:black'
lexers.STYLE_VARIABLE = 'fore:black'
lexers.STYLE_WHITESPACE = 'fore:white'
lexers.STYLE_EMBEDDED = 'fore:black'
lexers.STYLE_IDENTIFIER = 'fore:black'
