#! /bin/sh

allowcommittomaster=$(git config --bool hooks.allowcommittomaster)

if [ "$allowcommittomaster" != "true" ]; then
  # pre-commit: fail if current branch is master
  case "$(git rev-parse --abbrev-ref HEAD)" in
  master|main) echo "you forgot to make a branch!" 1>&2; exit 1;;
  esac
fi

# execute the repo hooks
if [ -x $GIT_DIR/hooks/pre-commit ]; then
    exec $GIT_DIR/hooks/pre-commit
fi

exit 0
